---
- hosts: webservers 
  become: True
  tasks:
    - name: Install packages for target VM Somak
      apt:
        name: "nginx"
        state: "present"
    - name: Install packages for target VM Somak
      apt:
        name: "httpd"
        state: "present"
   
...
