---
- hosts: webservers 
  become: True
  tasks:
    - name: Install packages for My Team for harshita
      apt:
        name: "nginx"
        state: "present"
    - name: Install packages
      apt:
        name: "apache2"
        state: "present"
   
...
