---
- hosts: webservers 
  become: True
  tasks:
    - name: Install packages for Team
      apt:
        name: "nginx"
        state: "present"
    - name: Install package 
      apt:
        name: "apache2"
        state: "present"
   
...
